spring:
  cloud:
    stream:
      bindings:
        input:
          destination: payments
          group: my-group-3
          consumer:
            resetOffsets: true
            startOffset: earliest
        output:
          destination: payments
          group: my-group


